---
- name: vm snapshot demo
  hosts: localhost
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yml
  vars_prompt:
          - name: vm_name
            prompt: enter the vm name?
            private: no
          - name: snap_name
            prompt: eneter the snap name?
            private: no
          - name: action
            prompt: do you want to create(present) | delete(absent) | delete-all(remove-all) | revert?
            private: no
  tasks:
    - name: remove snapshot
      vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        validate_certs: no
        name: "{{vm_name}}"
        folder:  "/{{ datacenter_name }}/vm/"
        snapshot_name: "{{snap_name}}"
        state: "{{action}}"
    - name: Info
      debug:
               msg: "{{vm_name}} vm snap updated" 
